### ISSUE TITLE
Foccacia sem sova

### ISSUE THREAD

**Issue by eliasdorneles** [fbidu/receitas#4]
Preciso muito dessa receita, ahaha <3

**Comment by fbidu** [comment]
@eliasdorneles consegui reproduzir a issue! hahahahah vou corrigir hoje a tarde :D

**Comment by fbidu** [comment]
Pronto, @eliasdorneles! Qualquer dúvida só falar :D https://github.com/fbidu/receitas/blob/main/p%C3%A3es%20e%20pizzas/focaccia-sem-sova.md

**Comment by eliasdorneles** [comment]
Valeeeeeuuuu!!! <3 <3
