### ISSUE TITLE
Uso do fermento na Focaccia

### ISSUE THREAD

**Issue by giovanisleite** [fbidu/receitas#5]
Opa, beleza? O fermento aqui vai junto com o restante (https://github.com/fbidu/receitas/blame/main/p%C3%A3es%20e%20pizzas/focaccia-sem-sova.md#L50)? Ou tu faz alguma esponja antes?

**Comment by fbidu** [comment]
Salve @giovanisleite!

Eu adiciono direto, sem hidratar ou fazer uma esponja antes. Em geral, é seguro usar todo tipo de 'fermento instantâneo' assim. Se você quiser uma fermentação um pouco mais rápida, fazer uma esponja pode ajudar, mas eu não acho que o resultado vai ser muuito diferente
